# Generated by Django 3.2 on 2022-06-27 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20220627_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sizes',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
